import requests

url_saml = "https://api17.sapsf.com/oauth/idp"

payload_saml='client_id=YmI5MTc3NDk4MzNjMzEzMDBiMjRlMTkxMDljMg&user_id=APPSAPCADF&token_url=https%3A%2F%2Fapi17.sapsf.com%2Fouth%2Ftoken&private_key=TUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFDem5PWWo0WWRGMmVVYU1tWXpuckthd013WnZGYVhMb0VYelM5WVlJSzFlc2s1eno5ajhKR3FUaG9wMEQwMndjektuRXlDWmhDYlRndkhsMkZGL0t6ekFrbmZDS3RPQnpJTXR4cWlpd3dueXV1T21Weks5eWc3cWVBTGp1UDdzY3BLcUdPc1VWZlpYdVJWRXhJYk93Zm9tQWJRaWFsbmtNdDFEVU5TWXRpV3lGNnkvbDViYnV0K3JoRy9yV3VkMXd4WStFWUxrRlB4N2dsQzc1TGxWcXNJSGgxclRacXdnMkRlSmhqT1BaQjdJOVV6bnRLMTN4bWQxYkVjSURZVTQrM0dtTHhhdW93MEhmZUFEYy9mQVdVK2x6VTQzVWhZRTlVVkgxNjJKeXJaa1NEd1dRVXdmS2N2bXpJKzZ6clk0QjlTVlp4bGx2bnRnV29Ca3pubjF6dWJBZ01CQUFFQ2dnRUJBSjBDeVVRUWdMb1ZNbXRtSjJWMGsxa290TUxDbTBkcGhid1N5QktQdTNOOXRLNXVkMUdjR1JveFVEbkJLZUhXSkhueGpBaHB4SmFlOFRrM0lmZVdYSEhLVEYxR0xNbjNERStGT1NsaU4rd0pQVVhZMXY4dWMrTkVLdkN2cHFoOTBRTFdsTnNyK0lteXBCT2lxaTlYdVNBZzFjUXlzdjR2MjB1bG5uWkVwbVdYcENzQm9abng4Rmt0U3k5VWEyaUw4ckJ1YnBvNnRGYnYralV3dDArRjErVmFBTjFUSU1mb0tOaHZVM0JnbVNKM0M3bUZzUGcyN0dJK0FQbTc5RjFDOHNkblg4YWhBZFROd3l4eSthaFpBNGJ6RFhJTTFxQWtFQUltY2dHZzBvS2psOG1wRWNRSUR4RHZLLzNLQVg4bWh5amFibjI5eGV6UVVwTmlnZzZOUWlFQ2dZRUE5OVBlbTBhcFgrdkhCZVdWZzRnKzZuM2VGOGRwRmZKRFJqS0MzcjZtUGZpc1FqQXZub2RZUVJYWmhET1h3akJnNlJhcUR1SFFkN0k5UGVuTDM1WXUyU3dGZ2g0cXZ1K2V1cWhCZXFTUmp2M0lmSzhEc2xQb3czN0ZtbTBmMzdWVG1FUlJONTRFVUFKeHIzREZBODVBSlBkRnU2OHlpdlBqUmxGK0s5Qm5RV01DZ1lFQXVZa3JSU2t2a0RtYkVrUVI2QlI5TERyaVJuYngvam5ZYk1OdHFHRks4dm5LZHpQRlhZaWFNdGVrcDdIZjd5WUozUCtGTVlNdGl2bE5tT2NsdU52akw2d2diVGFQdndPUURGbVVsNnM2UXArTHdSWVVOYW1KQVRSeHBVcWRsaEpaR2tKRUx4SGIwbm5BUmhlT3hhS0pKSDhTS3lna0g5cHh4UjR3cFdHT0Rta0NnWUVBeVcrdno3eFdyWDNDamx0MjlLdUlvQ2JnbjZsWkZCcVBiZjVlZTFpeFhVdkVFQ1NFZ0RGNG5hWjUzOGZqd1ZaN1h0b3FMZUNFQnRhY2lyZC9HK1JCZmdvWERCVWpINEU3SG5MbWpoNDNwZWRIejNpZDQ1UHFiUVNjN3hGbHgvcmwwSzB1NnFzSXpGUEFQaDdHTkhxdmpweGlWTlJwbTZIekNOUHlYd0NNL1FzQ2dZQXlqbUFPRG5UNWRkajlsekxSN0pOWE5BeG9hd3p4MjAxUUJjaWhzekU3R0RuRlZZUVlRcHJSODlUWUpTNEIrbm1Ca05iNGNPZytFRVRHdjJXV0E4VGFQcXJ2VjRpLzRmYWtodHhvbjYzV2JhY2xUQ0RocG5yQXEwdTBZS3FrTkFlM2tnc0dVSFYzMnRrN3dEdVZPdjdueFFCc1pobkIzRUpZRml2blJMZnkwUUtCZ0dkUTVBN2FML3Q0MEpsRFBBU1VjOWllcG5Lcit1Njc0L1Q0NXhiTFhwUEpleTFoNitlOWE0SDZWSXVwTWg1OFR3R3ppWkxqV1Z0RS9jNldDMVJ5NG83UWR6aDRVVllsQTRRcUo0aDJ1bm9HYklDUG9vQkJTT3JWMWNHaUxZeXBPWXd3eUdudzBXNnh3U05hZHBFcXhiMG9FanJPd2dqRUpLVThtNWNHSWxtTCMjI29udGFyaW9wb3dEMg=='
headers_saml = {
  'Content-Type': 'application/x-www-form-urlencoded'
}

response_saml = requests.request("POST", url_saml, headers=headers_saml, data=payload_saml)

print(response_saml.text)

url_token = "https://api17.sapsf.com/oauth/token"

payload_token='company_id=ontariopowD2&client_id=YmI5MTc3NDk4MzNjMzEzMDBiMjRlMTkxMDljMg&grant_type=urn:ietf:params:oauth:grant-type:saml2-bearer&assertion='+response_saml.text
headers_token = {
  'Content-Type': 'application/x-www-form-urlencoded'
}

response_token = requests.request("POST", url_token, headers=headers_token, data=payload_token)
print('Token')
print(response_token.text)
