import requests

url_saml = "https://api17.sapsf.com/oauth/idp"

payload_saml='client_id=YjhkZjc4MmVhZTUzMjMwNTIwNjQyMGMyNTBhYQ&user_id=APPSAPCADF&token_url=https%3A%2F%2Fapi17.sapsf.com%2Fouth%2Ftoken&private_key=TUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFDVFJQTllHTWppT2dmTEpmVVBXVlZjc0UzMTdMOXE5c1F2Z3I2Vy9hbm4wOVl4NU1yT2xpa3Y5dnJmWTlIejUxeGFKOG9RSVlkV2t5bHhTSEpIM2ZMeUFrUlJuY3RqTmtkeitldDA2U3JvVEtmQkxEcVhCREliaTlIbGpocHVHQkI5cXdjMm1zZEEyQm9xZ0pqQU1OSmJhdUVobkEvTzRWSmxxaEEvcUFYVnp0MVVlWm9vdlZrTkk4L0JMdDNQeE5UYU82OEV4Q3ZpUHg4TUVYelBHVjFoNmlwdWY1b1dmdEMyZHhnZnhhVGc2U0ZtdFBqcGd3MTBWWHlzMzBDeGdzNlRiakRmUmJFVGFWYjlkT3VLZmVpR2xSTUVhQk0yS1p1blQxTFdEeDl2ZjBLVDJiQ3ExMVMzUlRydjhWak9mNmNUb0RheVhucEJlUnlxdE16dEhWbTNBZ01CQUFFQ2dnRUFFb0MxT2pwUzh1bHJsVUI5bTZJVHNZT05KL3JJeWYyYkJJVWV3UVc1MVNDdVpySmlNTFo1RWtlcm1XbUhOV2U2R0xHckYzKys2MGV1QzBlWTVDS2twWGRYY2hHclBoblJ2R2FJQ0xaSzU4akp3dUYxc3dlWjdCQVRIUTVQajhtQ09PZkdEanhBRUl1V0xnVGVMRGQyRm5wRk10M1N0cUZrb3RWTkdWSlkrVlhGWk15WHF1a3Njbmt1ZldXTEk2bDVWUU9YZkdKT1JXcE5vQVlCVFkveGo2T1RBNmt6dHhEZGZycGlodzBQaCtKUUpPc3hnSkFvb3I3SWJRd3g3VU11N1FRcjV2T05MQXVIcmc1czhCN2VQa1pkcVVmUGZnNjNucE9OS0lhVFN3VzlWZG40aXp1aUpGOCtyRDZGQjRmdHd5eTJITzVTRVNOTlErSEUwY1pZRVFLQmdRRE9BVzVUVnhjL1RjdnhJaXkxZDQ1Z0U1RHhrbU9BWDdFRTFKUFprMElBR1FPTm4rM05MUmttdEVsdmFLdFZrU0t2cmNxMUdVSGlJNVAwdWx2ejlHMlZleFVkZ1RXcHVtNGZVaEdsV2tqamZlOVBYbXBrUGVDSlc1bTZaK2NYUG16dUNGdVhXMmhzNjdoV1ZtaHV3Ym9WVFkrZHZiK2grMTByWDh0T28rTVRKUUtCZ1FDM0FtVTlBbjlCM1lNOS9UWS9yKzVyWHh0RnY2emlQUFRiQjg4dG1iSTFFUWJkUUJzTndpU0svaVByZEFXbHhydVB4NXhHemtaNndVS0ZSMTcwcFF2ajFxYUdYaVJMd21zMjM3MjNoeFNNdldPcTZVbVZLelNQektNQzhiMTFoTXd0d2F5Sk12TGZsa2UzQ1d5RklOT1ZDUFVDM0hzUFFrWUcxU3ZCdEdSUXF3S0JnUUNTSEx1MmlyZm5ZM042SlNZVzA2UjlDb09zZzRybFczbS9sbE1EYUFuUTdlenlQM080S2Z1RDB5MmV3bHQ3aGtSVzNHcEJCcGdQSC9McUNsLzc2T3Jzc2U3cERXTVZiakI3TUlkcGcxN2RVODR2dWlTMTBwbDJjeXpXNUtrb2VGTmtoVE1KYUlEcGVFczNtWFBhMHJiOE14WGc2TnVKdFRLQStDSElOajl4clFLQmdCRml4dDllNTF3SWdUbFlYdGo2QzdwamxLR3hyZWpvUlpLeFVUdFJ5SjVGK2RMM0Rocm1nTFk3b29ueHdiK1grNldUSHdPVEFSc1VWUTk0VWtzSGl2T2dKcjNKSDhXYXVMakQxTEFrd3cwRHlQNHBuM1h1WHRYeWFPSVV1Uno2K3JLMkhZQURPUk9Jb1ZPQUw3RU9CMHUzU0I5M2RyRmlhR2lwdzdocFBNWjFBb0dBVGtLd0ROQ0lsM3VrWEFWcWdVWmVFZnBTY29vdDIwRTdjZVAwNXBJYVU2cWZFMjNTeFVPV21oaXNwNGRCOTBtYTZJVHVPa0N5TzBlUnVuVHYyLzFuWHZtUmJ1YVliNktPV3EvVWMxRFVhbnhkYWIzaEExN1B6cVEzK0o1emRXSFI4d3RBamtueERXWWh4Mlhja3c5S054SEdaWmwvZHEwUys1S2h1Y0c3UWxNPSMjI29udGFyaW9wb3dUOQ=='
headers_saml = {
  'Content-Type': 'application/x-www-form-urlencoded'
}

response_saml = requests.request("POST", url_saml, headers=headers_saml, data=payload_saml)

print(response_saml.text)

url_token = "https://api17.sapsf.com/oauth/token"

payload_token='company_id=ontariopowT9&client_id=YjhkZjc4MmVhZTUzMjMwNTIwNjQyMGMyNTBhYQ&grant_type=urn:ietf:params:oauth:grant-type:saml2-bearer&assertion='+response_saml.text
headers_token = {
  'Content-Type': 'application/x-www-form-urlencoded'
}

response_token = requests.request("POST", url_token, headers=headers_token, data=payload_token)
print('Token')
print(response_token.text)
